inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - 'gemfiles/**/*'

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^\s*#'
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Naming/FileName:
  Exclude:
    - 'lib/bemer-simple_form.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/action_view/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/action_view/**/*'
