langauge: ruby

sudo: false

cache: bundler

notifications:
  email: false

env:
  - CI='true'

rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.9
  - 2.6.10
  - 2.7.8
  - 3.0.6
  - 3.1.4
  - 3.2.2

gemfile:
  - gemfiles/simple_form_3.1.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_3.1.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_3.1.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_3.1.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_3.2.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_3.2.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_3.2.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_3.2.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_3.3.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_3.3.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_3.3.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_3.3.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_3.4.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_3.4.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_3.4.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_3.4.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_3.5.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_3.5.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_3.5.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_3.5.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_4.0.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_4.0.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_4.0.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_4.0.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_4.1.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_4.1.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_4.1.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_4.1.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_5.0.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_5.0.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_5.0.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_5.0.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_5.1.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_5.1.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_5.1.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_5.1.x_bemer_0.6.x.gemfile
  - gemfiles/simple_form_5.2.x_bemer_0.3.x.gemfile
  - gemfiles/simple_form_5.2.x_bemer_0.4.x.gemfile
  - gemfiles/simple_form_5.2.x_bemer_0.5.x.gemfile
  - gemfiles/simple_form_5.2.x_bemer_0.6.x.gemfile

matrix:
  exclude:
    ###########################################################
    # Ruby 2.3.8
    ###########################################################

    # Simple Form 4.0.x
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.3.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.4.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.5.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.6.x.gemfile

    # Simple Form 4.1.x
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.3.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.4.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.5.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.6.x.gemfile

    # Simple Form 5.0.x
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.3.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.4.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.5.x.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.6.x.gemfile

    ###########################################################
    # Ruby 2.4.10
    ###########################################################

    # Simple Form 4.0.x
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.3.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.4.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.5.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.0.x_bemer_0.6.x.gemfile

    # Simple Form 4.1.x
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.3.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.4.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.5.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_4.1.x_bemer_0.6.x.gemfile

    # Simple Form 5.0.x
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.3.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.4.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.5.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.0.x_bemer_0.6.x.gemfile

    # Simple Form 5.1.x
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.1.x_bemer_0.3.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.1.x_bemer_0.4.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.1.x_bemer_0.5.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.1.x_bemer_0.6.x.gemfile

    # Simple Form 5.2.x
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.2.x_bemer_0.3.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.2.x_bemer_0.4.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.2.x_bemer_0.5.x.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/simple_form_5.2.x_bemer_0.6.x.gemfile

    ###########################################################
    # Ruby 2.7.8
    ###########################################################

    # Simple Form 3.1.x
    - rvm: 2.7.8
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.3.x.gemfile
    - rvm: 2.7.8
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.4.x.gemfile
    - rvm: 2.7.8
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.5.x.gemfile
    - rvm: 2.7.8
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.6.x.gemfile

    ###########################################################
    # Ruby 3.0.6
    ###########################################################

    # Simple Form 3.1.x
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.3.x.gemfile
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.4.x.gemfile
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.5.x.gemfile
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.6.x.gemfile

    # Simple Form 3.5.x
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.3.x.gemfile
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.4.x.gemfile
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.5.x.gemfile
    - rvm: 3.0.6
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.6.x.gemfile

    ###########################################################
    # Ruby 3.1.4
    ###########################################################

    # Simple Form 3.1.x
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.3.x.gemfile
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.4.x.gemfile
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.5.x.gemfile
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.6.x.gemfile

    # Simple Form 3.5.x
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.3.x.gemfile
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.4.x.gemfile
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.5.x.gemfile
    - rvm: 3.1.4
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.6.x.gemfile

    ###########################################################
    # Ruby 3.2.2
    ###########################################################

    # Simple Form 3.1.x
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.3.x.gemfile
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.4.x.gemfile
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.5.x.gemfile
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.1.x_bemer_0.6.x.gemfile

    # Simple Form 3.5.x
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.3.x.gemfile
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.4.x.gemfile
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.5.x.gemfile
    - rvm: 3.2.2
      gemfile: gemfiles/simple_form_3.5.x_bemer_0.6.x.gemfile
