langauge: ruby

sudo: false

cache: bundler

notifications:
  email: false

env:
  - CI='true'

rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0

gemfile:
  - gemfiles/simple_form-0.4.x_bemer-0.1.x
  - gemfiles/simple_form-0.4.x_bemer-0.2.x
  - gemfiles/simple_form-0.4.x_bemer-0.3.x
  - gemfiles/simple_form-0.5.x_bemer-0.1.x
  - gemfiles/simple_form-0.5.x_bemer-0.2.x
  - gemfiles/simple_form-0.5.x_bemer-0.3.x
  - gemfiles/simple_form-1.0.x_bemer-0.1.x
  - gemfiles/simple_form-1.0.x_bemer-0.2.x
  - gemfiles/simple_form-1.0.x_bemer-0.3.x
  - gemfiles/simple_form-1.1.x_bemer-0.1.x
  - gemfiles/simple_form-1.1.x_bemer-0.2.x
  - gemfiles/simple_form-1.1.x_bemer-0.3.x
  - gemfiles/simple_form-1.2.x_bemer-0.1.x
  - gemfiles/simple_form-1.2.x_bemer-0.2.x
  - gemfiles/simple_form-1.2.x_bemer-0.3.x
  - gemfiles/simple_form-1.3.x_bemer-0.1.x
  - gemfiles/simple_form-1.3.x_bemer-0.2.x
  - gemfiles/simple_form-1.3.x_bemer-0.3.x
  - gemfiles/simple_form-1.4.x_bemer-0.1.x
  - gemfiles/simple_form-1.4.x_bemer-0.2.x
  - gemfiles/simple_form-1.4.x_bemer-0.3.x
  - gemfiles/simple_form-1.5.x_bemer-0.1.x
  - gemfiles/simple_form-1.5.x_bemer-0.2.x
  - gemfiles/simple_form-1.5.x_bemer-0.3.x
  - gemfiles/simple_form-2.0.x_bemer-0.1.x
  - gemfiles/simple_form-2.0.x_bemer-0.2.x
  - gemfiles/simple_form-2.0.x_bemer-0.3.x
  - gemfiles/simple_form-2.1.x_bemer-0.1.x
  - gemfiles/simple_form-2.1.x_bemer-0.2.x
  - gemfiles/simple_form-2.1.x_bemer-0.3.x
  - gemfiles/simple_form-3.0.x_bemer-0.1.x
  - gemfiles/simple_form-3.0.x_bemer-0.2.x
  - gemfiles/simple_form-3.0.x_bemer-0.3.x
  - gemfiles/simple_form-3.1.x_bemer-0.1.x
  - gemfiles/simple_form-3.1.x_bemer-0.2.x
  - gemfiles/simple_form-3.1.x_bemer-0.3.x
  - gemfiles/simple_form-3.2.x_bemer-0.1.x
  - gemfiles/simple_form-3.2.x_bemer-0.2.x
  - gemfiles/simple_form-3.2.x_bemer-0.3.x
  - gemfiles/simple_form-3.3.x_bemer-0.1.x
  - gemfiles/simple_form-3.3.x_bemer-0.2.x
  - gemfiles/simple_form-3.3.x_bemer-0.3.x
  - gemfiles/simple_form-3.4.x_bemer-0.1.x
  - gemfiles/simple_form-3.4.x_bemer-0.2.x
  - gemfiles/simple_form-3.4.x_bemer-0.3.x
  - gemfiles/simple_form-3.5.x_bemer-0.1.x
  - gemfiles/simple_form-3.5.x_bemer-0.2.x
  - gemfiles/simple_form-3.5.x_bemer-0.3.x
  - gemfiles/simple_form-4.0.x_bemer-0.1.x
  - gemfiles/simple_form-4.0.x_bemer-0.2.x
  - gemfiles/simple_form-4.0.x_bemer-0.3.x
  - gemfiles/simple_form-4.1.x_bemer-0.1.x
  - gemfiles/simple_form-4.1.x_bemer-0.2.x
  - gemfiles/simple_form-4.1.x_bemer-0.3.x
  - gemfiles/simple_form-5.0.x_bemer-0.1.x
  - gemfiles/simple_form-5.0.x_bemer-0.2.x
  - gemfiles/simple_form-5.0.x_bemer-0.3.x
